---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: coturn-auth
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: coturn
  replicas: 1 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: coturn
    spec:
      hostNetwork: true
      containers:
      - name: coturn-auth
        image: kurento/coturn-auth
        env:
        - name: "LISTENING_PORT"
          value: "3478"
        - name: "REALM"
          value: "kurento.org"
        - name: "USER"
          value: "nordri"
        - name: "PASSWORD"
          value: "s3cr3t"
        ports:
        - containerPort: 3478
      nodeSelector:
        networking: host
---
apiVersion: v1
kind: Service
metadata:
  name: coturn-auth
  labels:
    app: coturn
spec:
  ports:
    - port: 3478
      targetPort: 3478
      protocol: TCP
      name: coturn-port
  selector:
    app: coturn
  type: NodePort